language: node_js
node_js:
  - "10"
  - "11"
  - "12"

install:
  - yarn

script:
  - yarn lint
  - yarn test
  - yarn build

deploy:
  provider: script
  script: yarn semantic-release
  on:
    branch: master

cache:
  yarn: true
