language: node_js
node_js:
  - "10"
  - "11"
  - "12"

install:
  - yarn
  - yarn lint
  - yarn test
  - yarn build

deploy:
  provider: npm
  email: "david.ahern26@gmail.com"
  api_key: "60611249-7341-4d5f-af9f-040dee946487"
  on:
    branch: master

cache:
  yarn: true
