language: node_js
node_js:
  - "10"
  - "11"
  - "12"

install:
  - yarn

script:
  - yarn lint
  - yarn test
  - yarn build

deploy:
  provider: npm
  email: "david.ahern26@gmail.com"
  api_key: $NPM_TOKEN
  on:
    branch: master

cache:
  yarn: true
